<?xml version="1.0" encoding="utf-8"?><Database Name="ManageCafeInternet" Class="ManageCafeInternetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAB3_PC07;Initial Catalog=ManageCafeInternet;User ID=sa" SettingsObjectName="ManageCafeInternet.Properties.Settings" SettingsPropertyName="ManageCafeInternetConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.area" Member="areas">
    <Type Name="area">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="area_computer" Member="computers" ThisKey="entity_id" OtherKey="area_id" Type="computer" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="role_user" Member="role" ThisKey="role_id" OtherKey="entity_id" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.computer" Member="computers">
    <Type Name="computer">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="area_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="area_computer" Member="area" ThisKey="area_id" OtherKey="entity_id" Type="area" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.computer_status" Member="computer_status">
    <Type Name="computer_status">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="computer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="start_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="end_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="food_id" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="computer_status_order" Member="orders" ThisKey="entity_id" OtherKey="computer_status_id" Type="order" />
    </Type>
  </Table>
  <Table Name="dbo.food" Member="foods">
    <Type Name="food">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="food_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="food_type_food" Member="food_type" ThisKey="food_type_id" OtherKey="entity_id" Type="food_type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.food_type" Member="food_types">
    <Type Name="food_type">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="food_type_food" Member="foods" ThisKey="entity_id" OtherKey="food_type_id" Type="food" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="orders">
    <Type Name="order">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="computer_status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="computer_status_order" Member="computer_status" ThisKey="computer_status_id" OtherKey="entity_id" Type="computer_status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.role" Member="roles">
    <Type Name="role">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="role_user" Member="users" ThisKey="entity_id" OtherKey="role_id" Type="user" />
    </Type>
  </Table>
  <Function Name="dbo.addComputer" Method="addComputer">
    <Parameter Name="computer_name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="area_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateUser" Method="updateUser">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="account" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="firstName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="lastName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addFood" Method="addFood">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="image" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="foodTypeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addSelectedFoods" Method="addSelectedFoods">
    <Parameter Name="computerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="foodIdJson" Type="System.String" DbType="VarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addUser" Method="addUser">
    <Parameter Name="account" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="firstName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="lastName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteComputer" Method="deleteComputer">
    <Parameter Name="entity_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteFood" Method="deleteFood">
    <Parameter Name="entity_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteUser" Method="deleteUser">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getAllAreas" Method="getAllAreas">
    <ElementType Name="getAllAreasResult">
      <Column Name="area_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="area_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllComputers" Method="getAllComputers">
    <ElementType Name="getAllComputersResult">
      <Column Name="[Computer Id]" Member="Computer_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Computer Name]" Member="Computer_Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Computer Status]" Member="Computer_Status" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllComputersFromArea" Method="getAllComputersFromArea">
    <Parameter Name="area_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getAllComputersFromAreaResult">
      <Column Name="[Computer Id]" Member="Computer_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Computer Name]" Member="Computer_Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Computer Status]" Member="Computer_Status" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllFoods" Method="getAllFoods">
    <ElementType Name="getAllFoodsResult">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Foods Name]" Member="Foods_Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="food_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Foods Type]" Member="Foods_Type" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllFoodTypes" Method="getAllFoodTypes">
    <ElementType Name="getAllFoodTypesResult">
      <Column Name="food_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="food_type_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllRoles" Method="getAllRoles">
    <ElementType Name="getAllRolesResult">
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="role_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllUsersFromRole" Method="getAllUsersFromRole">
    <Parameter Name="role_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="getAllUsersFromRoleResult">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getSelectedFoodsByComputerId" Method="getSelectedFoodsByComputerId">
    <Parameter Name="computerId" Type="System.Int32" DbType="Int" />
    <ElementType Name="getSelectedFoodsByComputerIdResult">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="food_id" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getUser" Method="getUser">
    <Parameter Name="account" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="getUserResult">
      <Column Name="entity_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getUserFromRole" Method="getUserFromRole">
    <Parameter Name="roleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="getUserFromRoleResult">
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="role_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.updateComputer" Method="updateComputer">
    <Parameter Name="entity_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="computer_name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="area_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateComputerStartTime" Method="updateComputerStartTime">
    <Parameter Name="computer_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="start_time" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateComputerStatus" Method="updateComputerStatus">
    <Parameter Name="computer_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateFood" Method="updateFood">
    <Parameter Name="entity_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="image" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="foodTypeId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateFoodQuantity" Method="updateFoodQuantity">
    <Parameter Name="foodId" Type="System.Int32" DbType="Int" />
    <Parameter Name="quanity" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>